### ISSUE TITLE
Extraction width BUG

### ISSUE THREAD

**Issue by asaccardi** [JPalmerio/zHunter#3]
There is a bug with the extraction witdh box. If you change the extraction, it changes in the 2D and in 1D. Then if you want to retourn at the default one clicking the box "reset width" it changes the 2D but not the 1D. Also the number in the box doesn't change. 

Traceback (most recent call last):
  File "zhunter.py", line 438, in reset_width
    self.roi.sigRegionChanged.connect(self.updatePlot)
AttributeError: 'MainWindow' object has no attribute 'updatePlot'

This is the output of the error.

**Comment by JPalmerio** [comment]
Thanks for reporting this, it has been fixed.
